/* tslint:disable */
/* eslint-disable */
/*
Gusto API

Welcome to Gusto's Embedded Payroll API documentation!

The version of the OpenAPI document: 2024-03-01
Contact: developer@gusto.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, isBrowser } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { AchTransaction } from '../models';
import { paginate } from "../pagination/paginate";
import type * as buffer from "buffer"
import { requestBeforeHook } from '../requestBeforeHook';
/**
 * AchTransactionsApi - axios parameter creator
 * @export
 */
export const AchTransactionsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Fetches all ACH transactions for a company.  scope: `ach_transactions:read`
         * @summary Get all ACH transactions for a company
         * @param {string} companyUuid The UUID of the company
         * @param {string} [contractorPaymentUuid] The UUID of the contractor payment
         * @param {string} [payrollUuid] The UUID of the payroll
         * @param {string} [transactionType] Used to filter the ACH transactions to only include those with a specific transaction type, such as \&quot;Credit employee pay\&quot;.
         * @param {string} [paymentDirection] Used to filter the ACH transactions to only include those with a specific payment direction, either \&quot;credit\&quot; or \&quot;debit\&quot;.
         * @param {'2024-03-01'} [xGustoApiVersion] Determines the date-based API version associated with your API call. If none is provided, your application\&#39;s [minimum API version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllForCompany: async (companyUuid: string, contractorPaymentUuid?: string, payrollUuid?: string, transactionType?: string, paymentDirection?: string, xGustoApiVersion?: '2024-03-01', options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'companyUuid' is not null or undefined
            assertParamExists('getAllForCompany', 'companyUuid', companyUuid)
            const localVarPath = `/v1/companies/{company_uuid}/ach_transactions`
                .replace(`{${"company_uuid"}}`, encodeURIComponent(String(companyUuid !== undefined ? companyUuid : `-company_uuid-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Authorization required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)
            if (contractorPaymentUuid !== undefined) {
                localVarQueryParameter['contractor_payment_uuid'] = contractorPaymentUuid;
            }

            if (payrollUuid !== undefined) {
                localVarQueryParameter['payroll_uuid'] = payrollUuid;
            }

            if (transactionType !== undefined) {
                localVarQueryParameter['transaction_type'] = transactionType;
            }

            if (paymentDirection !== undefined) {
                localVarQueryParameter['payment_direction'] = paymentDirection;
            }

            if (xGustoApiVersion != null) {
                localVarHeaderParameter['X-Gusto-API-Version'] = String(xGustoApiVersion);
            }


    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/v1/companies/{company_uuid}/ach_transactions',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AchTransactionsApi - functional programming interface
 * @export
 */
export const AchTransactionsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AchTransactionsApiAxiosParamCreator(configuration)
    return {
        /**
         * Fetches all ACH transactions for a company.  scope: `ach_transactions:read`
         * @summary Get all ACH transactions for a company
         * @param {AchTransactionsApiGetAllForCompanyRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAllForCompany(requestParameters: AchTransactionsApiGetAllForCompanyRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<AchTransaction>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAllForCompany(requestParameters.companyUuid, requestParameters.contractorPaymentUuid, requestParameters.payrollUuid, requestParameters.transactionType, requestParameters.paymentDirection, requestParameters.xGustoApiVersion, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * AchTransactionsApi - factory interface
 * @export
 */
export const AchTransactionsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AchTransactionsApiFp(configuration)
    return {
        /**
         * Fetches all ACH transactions for a company.  scope: `ach_transactions:read`
         * @summary Get all ACH transactions for a company
         * @param {AchTransactionsApiGetAllForCompanyRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAllForCompany(requestParameters: AchTransactionsApiGetAllForCompanyRequest, options?: AxiosRequestConfig): AxiosPromise<Array<AchTransaction>> {
            return localVarFp.getAllForCompany(requestParameters, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for getAllForCompany operation in AchTransactionsApi.
 * @export
 * @interface AchTransactionsApiGetAllForCompanyRequest
 */
export type AchTransactionsApiGetAllForCompanyRequest = {
    
    /**
    * The UUID of the company
    * @type {string}
    * @memberof AchTransactionsApiGetAllForCompany
    */
    readonly companyUuid: string
    
    /**
    * The UUID of the contractor payment
    * @type {string}
    * @memberof AchTransactionsApiGetAllForCompany
    */
    readonly contractorPaymentUuid?: string
    
    /**
    * The UUID of the payroll
    * @type {string}
    * @memberof AchTransactionsApiGetAllForCompany
    */
    readonly payrollUuid?: string
    
    /**
    * Used to filter the ACH transactions to only include those with a specific transaction type, such as \"Credit employee pay\".
    * @type {string}
    * @memberof AchTransactionsApiGetAllForCompany
    */
    readonly transactionType?: string
    
    /**
    * Used to filter the ACH transactions to only include those with a specific payment direction, either \"credit\" or \"debit\".
    * @type {string}
    * @memberof AchTransactionsApiGetAllForCompany
    */
    readonly paymentDirection?: string
    
    /**
    * Determines the date-based API version associated with your API call. If none is provided, your application\'s [minimum API version](https://docs.gusto.com/embedded-payroll/docs/api-versioning#minimum-api-version) is used.
    * @type {'2024-03-01'}
    * @memberof AchTransactionsApiGetAllForCompany
    */
    readonly xGustoApiVersion?: '2024-03-01'
    
}

/**
 * AchTransactionsApiGenerated - object-oriented interface
 * @export
 * @class AchTransactionsApiGenerated
 * @extends {BaseAPI}
 */
export class AchTransactionsApiGenerated extends BaseAPI {
    /**
     * Fetches all ACH transactions for a company.  scope: `ach_transactions:read`
     * @summary Get all ACH transactions for a company
     * @param {AchTransactionsApiGetAllForCompanyRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AchTransactionsApiGenerated
     */
    public getAllForCompany(requestParameters: AchTransactionsApiGetAllForCompanyRequest, options?: AxiosRequestConfig) {
        return AchTransactionsApiFp(this.configuration).getAllForCompany(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }
}
