/*
Gusto API

Welcome to Gusto's Embedded Payroll API documentation!

The version of the OpenAPI document: 2024-03-01
Contact: developer@gusto.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AddressAllOf } from './address-all-of';
import { Versionable } from './versionable';

/**
 * @type Address
 * @export
 */
export type Address = AddressAllOf & Versionable;


