/*
Gusto API

Welcome to Gusto's Embedded Payroll API documentation!

The version of the OpenAPI document: 2024-03-01
Contact: developer@gusto.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The representation of an admin user in Gusto.
 * @export
 * @interface Admin
 */
export interface Admin {
    /**
     * The unique id of the admin.
     * @type {string}
     * @memberof Admin
     */
    'uuid'?: string;
    /**
     * The email of the admin for Gusto\'s system. If the email matches an existing user, this will create an admin account for them.
     * @type {string}
     * @memberof Admin
     */
    'email'?: string;
    /**
     * The first name of the admin.
     * @type {string}
     * @memberof Admin
     */
    'first_name'?: string;
    /**
     * The last name of the admin.
     * @type {string}
     * @memberof Admin
     */
    'last_name'?: string;
}

