/*
Gusto API

Welcome to Gusto's Embedded Payroll API documentation!

The version of the OpenAPI document: 2024-03-01
Contact: developer@gusto.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { BenefitSummaryEmployeesPayrollBenefitsPayPeriod } from './benefit-summary-employees-payroll-benefits-pay-period';

/**
 * 
 * @export
 * @interface BenefitSummaryEmployeesPayrollBenefits
 */
export interface BenefitSummaryEmployeesPayrollBenefits {
    /**
     * 
     * @type {string}
     * @memberof BenefitSummaryEmployeesPayrollBenefits
     */
    'payroll_uuid'?: string;
    /**
     * Whether it is regular or bonus payroll
     * @type {string}
     * @memberof BenefitSummaryEmployeesPayrollBenefits
     */
    'payroll_type'?: string;
    /**
     * 
     * @type {string}
     * @memberof BenefitSummaryEmployeesPayrollBenefits
     */
    'check_date'?: string;
    /**
     * 
     * @type {string}
     * @memberof BenefitSummaryEmployeesPayrollBenefits
     */
    'gross_pay'?: string;
    /**
     * 
     * @type {string}
     * @memberof BenefitSummaryEmployeesPayrollBenefits
     */
    'company_benefit_deduction'?: string;
    /**
     * 
     * @type {string}
     * @memberof BenefitSummaryEmployeesPayrollBenefits
     */
    'company_benefit_contribution'?: string;
    /**
     * 
     * @type {BenefitSummaryEmployeesPayrollBenefitsPayPeriod}
     * @memberof BenefitSummaryEmployeesPayrollBenefits
     */
    'pay_period'?: BenefitSummaryEmployeesPayrollBenefitsPayPeriod;
}

