/*
Gusto API

Welcome to Gusto's Embedded Payroll API documentation!

The version of the OpenAPI document: 2024-03-01
Contact: developer@gusto.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { BenefitSummaryEmployees } from './benefit-summary-employees';

/**
 * 
 * @export
 * @interface BenefitSummary
 */
export interface BenefitSummary {
    /**
     * Description of the benefit.
     * @type {string}
     * @memberof BenefitSummary
     */
    'description'?: string;
    /**
     * The start date of benefit summary.
     * @type {string}
     * @memberof BenefitSummary
     */
    'start_date'?: string;
    /**
     * The end date of benefit summary.
     * @type {string}
     * @memberof BenefitSummary
     */
    'end_date'?: string;
    /**
     * The aggregate of employee deduction for all employees given the period of time and benefit type.
     * @type {string}
     * @memberof BenefitSummary
     */
    'company_benefit_deduction'?: string;
    /**
     * The aggregate of company contribution for all employees given the period of time and benefit type.
     * @type {string}
     * @memberof BenefitSummary
     */
    'company_benefit_contribution'?: string;
    /**
     * 
     * @type {BenefitSummaryEmployees}
     * @memberof BenefitSummary
     */
    'employees'?: BenefitSummaryEmployees;
}

