/*
Gusto API

Welcome to Gusto's Embedded Payroll API documentation!

The version of the OpenAPI document: 2024-03-01
Contact: developer@gusto.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CompanyCompensationsHourlyInner
 */
export interface CompanyCompensationsHourlyInner {
    /**
     * The name of the hourly compensation rate.
     * @type {string}
     * @memberof CompanyCompensationsHourlyInner
     */
    'name'?: string;
    /**
     * The amount multiplied by the base rate of a job to calculate compensation.
     * @type {number}
     * @memberof CompanyCompensationsHourlyInner
     */
    'multiple'?: number;
}

