/*
Gusto API

Welcome to Gusto's Embedded Payroll API documentation!

The version of the OpenAPI document: 2024-03-01
Contact: developer@gusto.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CompanyPrimarySignatoryHomeAddress
 */
export interface CompanyPrimarySignatoryHomeAddress {
    /**
     * 
     * @type {string}
     * @memberof CompanyPrimarySignatoryHomeAddress
     */
    'street_1'?: string;
    /**
     * 
     * @type {string}
     * @memberof CompanyPrimarySignatoryHomeAddress
     */
    'street_2'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CompanyPrimarySignatoryHomeAddress
     */
    'city'?: string;
    /**
     * 
     * @type {string}
     * @memberof CompanyPrimarySignatoryHomeAddress
     */
    'state'?: string;
    /**
     * 
     * @type {string}
     * @memberof CompanyPrimarySignatoryHomeAddress
     */
    'zip'?: string;
    /**
     * 
     * @type {string}
     * @memberof CompanyPrimarySignatoryHomeAddress
     */
    'country'?: string;
}

