/*
Gusto API

Welcome to Gusto's Embedded Payroll API documentation!

The version of the OpenAPI document: 2024-03-01
Contact: developer@gusto.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CompanyCompensationsFixedInner } from './company-compensations-fixed-inner';
import { CompanyCompensationsHourlyInner } from './company-compensations-hourly-inner';
import { CompanyCompensationsPaidTimeOffInner } from './company-compensations-paid-time-off-inner';

/**
 * The available company-wide compensation rates for the company.
 * @export
 * @interface CompanyCompensations
 */
export interface CompanyCompensations {
    /**
     * The available hourly compensation rates for the company.
     * @type {Set<CompanyCompensationsHourlyInner>}
     * @memberof CompanyCompensations
     */
    'hourly'?: Set<CompanyCompensationsHourlyInner>;
    /**
     * The available fixed compensation rates for the company.
     * @type {Set<CompanyCompensationsFixedInner>}
     * @memberof CompanyCompensations
     */
    'fixed'?: Set<CompanyCompensationsFixedInner>;
    /**
     * The available types of paid time off for the company.
     * @type {Set<CompanyCompensationsPaidTimeOffInner>}
     * @memberof CompanyCompensations
     */
    'paid_time_off'?: Set<CompanyCompensationsPaidTimeOffInner>;
}

