/*
Gusto API

Welcome to Gusto's Embedded Payroll API documentation!

The version of the OpenAPI document: 2024-03-01
Contact: developer@gusto.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CompaniesMigrateToEmbeddedPayrollRequest
 */
export interface CompaniesMigrateToEmbeddedPayrollRequest {
    /**
     * Email of the company signatory who is authorized to accept our [Terms of Service](https://flows.gusto.com/terms) and migration decision. You can retrieve the signatory email from the `GET /v/1/companies/{company_id}/signatories` endpoint.
     * @type {string}
     * @memberof CompaniesMigrateToEmbeddedPayrollRequest
     */
    'email': string;
    /**
     * The IP address of the signatory who viewed and accepted the Terms of Service.
     * @type {string}
     * @memberof CompaniesMigrateToEmbeddedPayrollRequest
     */
    'ip_address': string;
    /**
     * The signatory\'s user ID on your platform.
     * @type {string}
     * @memberof CompaniesMigrateToEmbeddedPayrollRequest
     */
    'external_user_id': string;
}

