/*
Gusto API

Welcome to Gusto's Embedded Payroll API documentation!

The version of the OpenAPI document: 2024-03-01
Contact: developer@gusto.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CompaniesAcceptTermsOfServiceResponse
 */
export interface CompaniesAcceptTermsOfServiceResponse {
    /**
     * Whether the latest terms have been accepted by the user.
     * @type {boolean}
     * @memberof CompaniesAcceptTermsOfServiceResponse
     */
    'latest_terms_accepted'?: boolean;
}

