/*
Gusto API

Welcome to Gusto's Embedded Payroll API documentation!

The version of the OpenAPI document: 2024-03-01
Contact: developer@gusto.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CompanyBenefitWithEmployeeBenefitsEmployeeBenefitsInnerContributionValueOneOfTiersInner } from './company-benefit-with-employee-benefits-employee-benefits-inner-contribution-value-one-of-tiers-inner';

/**
 * 
 * @export
 * @interface CompanyBenefitWithEmployeeBenefitsEmployeeBenefitsInnerContributionValueOneOf
 */
export interface CompanyBenefitWithEmployeeBenefitsEmployeeBenefitsInnerContributionValueOneOf {
    /**
     * 
     * @type {Array<CompanyBenefitWithEmployeeBenefitsEmployeeBenefitsInnerContributionValueOneOfTiersInner>}
     * @memberof CompanyBenefitWithEmployeeBenefitsEmployeeBenefitsInnerContributionValueOneOf
     */
    'tiers'?: Array<CompanyBenefitWithEmployeeBenefitsEmployeeBenefitsInnerContributionValueOneOfTiersInner>;
}

