/*
Gusto API

Welcome to Gusto's Embedded Payroll API documentation!

The version of the OpenAPI document: 2024-03-01
Contact: developer@gusto.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The representation of a single contractor payment.
 * @export
 * @interface ContractorPayment
 */
export interface ContractorPayment {
    /**
     * The unique identifier of the contractor payment in Gusto.
     * @type {string}
     * @memberof ContractorPayment
     */
    'uuid'?: string;
    /**
     * The UUID of the contractor.
     * @type {string}
     * @memberof ContractorPayment
     */
    'contractor_uuid'?: string;
    /**
     * The bonus amount in the payment.
     * @type {string}
     * @memberof ContractorPayment
     */
    'bonus'?: string;
    /**
     * The payment date.
     * @type {string}
     * @memberof ContractorPayment
     */
    'date'?: string;
    /**
     * The number of hours worked for the payment.
     * @type {string}
     * @memberof ContractorPayment
     */
    'hours'?: string;
    /**
     * The payment method.
     * @type {string}
     * @memberof ContractorPayment
     */
    'payment_method'?: ContractorPaymentPaymentMethodEnum;
    /**
     * The reimbursement amount in the payment.
     * @type {string}
     * @memberof ContractorPayment
     */
    'reimbursement'?: string;
    /**
     * Contractor payment status
     * @type {string}
     * @memberof ContractorPayment
     */
    'status'?: ContractorPaymentStatusEnum;
    /**
     * The rate per hour worked for the payment.
     * @type {string}
     * @memberof ContractorPayment
     */
    'hourly_rate'?: string;
    /**
     * Determine if the contractor payment can be cancelled.
     * @type {boolean}
     * @memberof ContractorPayment
     */
    'may_cancel'?: boolean;
    /**
     * The fixed wage of the payment, regardless of hours worked.
     * @type {string}
     * @memberof ContractorPayment
     */
    'wage'?: string;
    /**
     * The wage type for the payment.
     * @type {string}
     * @memberof ContractorPayment
     */
    'wage_type'?: ContractorPaymentWageTypeEnum;
    /**
     * (hours * hourly_rate) + wage + bonus
     * @type {string}
     * @memberof ContractorPayment
     */
    'wage_total'?: string;
}

type ContractorPaymentPaymentMethodEnum = 'Direct Deposit' | 'Check' | 'Historical Payment' | 'Correction Payment'
type ContractorPaymentStatusEnum = 'Funded' | 'Unfunded'
type ContractorPaymentWageTypeEnum = 'Hourly' | 'Fixed'


