/*
Gusto API

Welcome to Gusto's Embedded Payroll API documentation!

The version of the OpenAPI document: 2024-03-01
Contact: developer@gusto.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ContractorBankAccount
 */
export interface ContractorBankAccount {
    /**
     * UUID of the bank account
     * @type {string}
     * @memberof ContractorBankAccount
     */
    'uuid'?: string;
    /**
     * UUID of the employee
     * @type {string}
     * @memberof ContractorBankAccount
     */
    'contractor_uuid'?: string;
    /**
     * Bank account type
     * @type {string}
     * @memberof ContractorBankAccount
     */
    'account_type'?: ContractorBankAccountAccountTypeEnum;
    /**
     * Name for the bank account
     * @type {string}
     * @memberof ContractorBankAccount
     */
    'name'?: string;
    /**
     * The bank account\'s routing number
     * @type {string}
     * @memberof ContractorBankAccount
     */
    'routing_number'?: string;
    /**
     * Masked bank account number
     * @type {string}
     * @memberof ContractorBankAccount
     */
    'hidden_account_number'?: string;
}

type ContractorBankAccountAccountTypeEnum = 'Checking' | 'Savings'


