/*
Gusto API

Welcome to Gusto's Embedded Payroll API documentation!

The version of the OpenAPI document: 2024-03-01
Contact: developer@gusto.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The wage and reimbursement totals for all contractor payments within a given time period.
 * @export
 * @interface ContractorPaymentSummaryByDatesTotal
 */
export interface ContractorPaymentSummaryByDatesTotal {
    /**
     * The total reimbursements for contractor payments within a given time period.
     * @type {string}
     * @memberof ContractorPaymentSummaryByDatesTotal
     */
    'reimbursements'?: string;
    /**
     * The total wages for contractor payments within a given time period.
     * @type {string}
     * @memberof ContractorPaymentSummaryByDatesTotal
     */
    'wages'?: string;
}

