/*
Gusto API

Welcome to Gusto's Embedded Payroll API documentation!

The version of the OpenAPI document: 2024-03-01
Contact: developer@gusto.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CompanyBenefitsDeleteBenefitResponseErrorsBaseInner } from './company-benefits-delete-benefit-response-errors-base-inner';

/**
 * 
 * @export
 * @interface ContractorPaymentsPreviewDebitDate422ResponseErrors
 */
export interface ContractorPaymentsPreviewDebitDate422ResponseErrors {
    /**
     * 
     * @type {Array<CompanyBenefitsDeleteBenefitResponseErrorsBaseInner>}
     * @memberof ContractorPaymentsPreviewDebitDate422ResponseErrors
     */
    'base'?: Array<CompanyBenefitsDeleteBenefitResponseErrorsBaseInner>;
    /**
     * 
     * @type {Array<CompanyBenefitsDeleteBenefitResponseErrorsBaseInner>}
     * @memberof ContractorPaymentsPreviewDebitDate422ResponseErrors
     */
    'check_date'?: Array<CompanyBenefitsDeleteBenefitResponseErrorsBaseInner>;
}

