/*
Gusto API

Welcome to Gusto's Embedded Payroll API documentation!

The version of the OpenAPI document: 2024-03-01
Contact: developer@gusto.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface EmployeesUpdateOnboardingStatusRequest
 */
export interface EmployeesUpdateOnboardingStatusRequest {
    /**
     * The updated onboarding status for the employee
     * @type {string}
     * @memberof EmployeesUpdateOnboardingStatusRequest
     */
    'onboarding_status': string;
}

