/*
Gusto API

Welcome to Gusto's Embedded Payroll API documentation!

The version of the OpenAPI document: 2024-03-01
Contact: developer@gusto.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EmployeeTaxSetupUpdateStateTaxesRequestStatesInner } from './employee-tax-setup-update-state-taxes-request-states-inner';

/**
 * 
 * @export
 * @interface EmployeeTaxSetupUpdateStateTaxesRequest
 */
export interface EmployeeTaxSetupUpdateStateTaxesRequest {
    /**
     * 
     * @type {Set<EmployeeTaxSetupUpdateStateTaxesRequestStatesInner>}
     * @memberof EmployeeTaxSetupUpdateStateTaxesRequest
     */
    'states': Set<EmployeeTaxSetupUpdateStateTaxesRequestStatesInner>;
}

