/*
Gusto API

Welcome to Gusto's Embedded Payroll API documentation!

The version of the OpenAPI document: 2024-03-01
Contact: developer@gusto.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface EmployeeFormsGenerateW2DocumentResponseAllOf
 */
export interface EmployeeFormsGenerateW2DocumentResponseAllOf {
    /**
     * The UUID of the employee
     * @type {string}
     * @memberof EmployeeFormsGenerateW2DocumentResponseAllOf
     */
    'employee_uuid'?: string;
}

