/*
Gusto API

Welcome to Gusto's Embedded Payroll API documentation!

The version of the OpenAPI document: 2024-03-01
Contact: developer@gusto.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface EmployeePaymentMethodUpdatePaymentMethodRequestSplitsInner
 */
export interface EmployeePaymentMethodUpdatePaymentMethodRequestSplitsInner {
    /**
     * The bank account ID 
     * @type {string}
     * @memberof EmployeePaymentMethodUpdatePaymentMethodRequestSplitsInner
     */
    'uuid'?: string;
    /**
     * The bank account name
     * @type {string}
     * @memberof EmployeePaymentMethodUpdatePaymentMethodRequestSplitsInner
     */
    'name'?: string;
    /**
     * The order of priority for each payment split, with priority 1 being the first bank account paid. Priority must be unique and sequential.
     * @type {number}
     * @memberof EmployeePaymentMethodUpdatePaymentMethodRequestSplitsInner
     */
    'priority'?: number;
    /**
     * The cents amount allocated for each payment split
     * @type {number}
     * @memberof EmployeePaymentMethodUpdatePaymentMethodRequestSplitsInner
     */
    'split_amount'?: number | null;
}

