/*
Gusto API

Welcome to Gusto's Embedded Payroll API documentation!

The version of the OpenAPI document: 2024-03-01
Contact: developer@gusto.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Representation of an Event
 * @export
 * @interface Event
 */
export interface Event {
    /**
     * Unique identifier for the event.
     * @type {string}
     * @memberof Event
     */
    'uuid'?: string;
    /**
     * Description of the event (e.g., payroll.submitted, or company.form.signed).
     * @type {string}
     * @memberof Event
     */
    'event_type'?: string;
    /**
     * Name of the parent resource of the described entity.
     * @type {string}
     * @memberof Event
     */
    'resource_type'?: EventResourceTypeEnum;
    /**
     * Unique identifier for the parent resource.
     * @type {string}
     * @memberof Event
     */
    'resource_uuid'?: string;
    /**
     * Name of the entity that the event corresponds to.
     * @type {string}
     * @memberof Event
     */
    'entity_type'?: string;
    /**
     * Unique identifier for the entity.
     * @type {string}
     * @memberof Event
     */
    'entity_uuid'?: string;
    /**
     * Time at which this event was created. Measured in seconds since the Unix epoch.
     * @type {number}
     * @memberof Event
     */
    'timestamp'?: number;
}

type EventResourceTypeEnum = 'Company'


