/*
Gusto API

Welcome to Gusto's Embedded Payroll API documentation!

The version of the OpenAPI document: 2024-03-01
Contact: developer@gusto.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ExternalPayrollApplicableBenefitsInner
 */
export interface ExternalPayrollApplicableBenefitsInner {
    /**
     * 
     * @type {string}
     * @memberof ExternalPayrollApplicableBenefitsInner
     */
    'description'?: string;
    /**
     * 
     * @type {number}
     * @memberof ExternalPayrollApplicableBenefitsInner
     */
    'id'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ExternalPayrollApplicableBenefitsInner
     */
    'active'?: boolean;
}

