/*
Gusto API

Welcome to Gusto's Embedded Payroll API documentation!

The version of the OpenAPI document: 2024-03-01
Contact: developer@gusto.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Stores metadata of the external payroll.
 * @export
 * @interface ExternalPayrollMetadata
 */
export interface ExternalPayrollMetadata {
    /**
     * Determines if the external payroll can be deleted.
     * @type {boolean}
     * @memberof ExternalPayrollMetadata
     */
    'deletable'?: boolean;
}

