/*
Gusto API

Welcome to Gusto's Embedded Payroll API documentation!

The version of the OpenAPI document: 2024-03-01
Contact: developer@gusto.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface FormPdf
 */
export interface FormPdf {
    /**
     * the UUID of the form
     * @type {string}
     * @memberof FormPdf
     */
    'uuid'?: string;
    /**
     * the URL of the form
     * @type {string}
     * @memberof FormPdf
     */
    'document_url'?: string;
}

