/*
Gusto API

Welcome to Gusto's Embedded Payroll API documentation!

The version of the OpenAPI document: 2024-03-01
Contact: developer@gusto.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface GarnishmentsUpdateGarnishmentRequest
 */
export interface GarnishmentsUpdateGarnishmentRequest {
    /**
     * The description of the garnishment.
     * @type {string}
     * @memberof GarnishmentsUpdateGarnishmentRequest
     */
    'description'?: string;
    /**
     * The current version of the object. See the [versioning guide](https://docs.gusto.com/embedded-payroll/docs/versioning#object-layer) for information on how to use this field.
     * @type {string}
     * @memberof GarnishmentsUpdateGarnishmentRequest
     */
    'version': string;
    /**
     * Whether or not this garnishment is currently active.
     * @type {boolean}
     * @memberof GarnishmentsUpdateGarnishmentRequest
     */
    'active'?: boolean;
    /**
     * The amount of the garnishment. Either a percentage or a fixed dollar amount. Represented as a float, e.g. \"8.00\".
     * @type {number}
     * @memberof GarnishmentsUpdateGarnishmentRequest
     */
    'amount'?: number;
    /**
     * Whether the garnishment is court ordered.
     * @type {boolean}
     * @memberof GarnishmentsUpdateGarnishmentRequest
     */
    'court_ordered'?: boolean;
    /**
     * The number of times to apply the garnishment. Ignored if recurring is true.
     * @type {number}
     * @memberof GarnishmentsUpdateGarnishmentRequest
     */
    'times'?: number | null;
    /**
     * Whether the garnishment should recur indefinitely.
     * @type {boolean}
     * @memberof GarnishmentsUpdateGarnishmentRequest
     */
    'recurring'?: boolean;
    /**
     * The maximum deduction per annum. A null value indicates no maximum. Represented as a float, e.g. \"200.00\".
     * @type {number}
     * @memberof GarnishmentsUpdateGarnishmentRequest
     */
    'annual_maximum'?: number | null;
    /**
     * The maximum deduction per pay period. A null value indicates no maximum. Represented as a float, e.g. \"16.00\".
     * @type {number}
     * @memberof GarnishmentsUpdateGarnishmentRequest
     */
    'pay_period_maximum'?: number | null;
    /**
     * Whether the amount should be treated as a percentage to be deducted per pay period.
     * @type {boolean}
     * @memberof GarnishmentsUpdateGarnishmentRequest
     */
    'deduct_as_percentage'?: boolean;
}

