/*
Gusto API

Welcome to Gusto's Embedded Payroll API documentation!

The version of the OpenAPI document: 2024-03-01
Contact: developer@gusto.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { HolidayPayPolicyFederalHolidaysInnerNewYearsDay } from './holiday-pay-policy-federal-holidays-inner-new-years-day';

/**
 * 
 * @export
 * @interface HolidayPayPolicyFederalHolidaysInner
 */
export interface HolidayPayPolicyFederalHolidaysInner {
    /**
     * 
     * @type {HolidayPayPolicyFederalHolidaysInnerNewYearsDay}
     * @memberof HolidayPayPolicyFederalHolidaysInner
     */
    'new_years_day'?: HolidayPayPolicyFederalHolidaysInnerNewYearsDay;
    /**
     * 
     * @type {HolidayPayPolicyFederalHolidaysInnerNewYearsDay}
     * @memberof HolidayPayPolicyFederalHolidaysInner
     */
    'mlk_day'?: HolidayPayPolicyFederalHolidaysInnerNewYearsDay;
    /**
     * 
     * @type {HolidayPayPolicyFederalHolidaysInnerNewYearsDay}
     * @memberof HolidayPayPolicyFederalHolidaysInner
     */
    'presidents_day'?: HolidayPayPolicyFederalHolidaysInnerNewYearsDay;
    /**
     * 
     * @type {HolidayPayPolicyFederalHolidaysInnerNewYearsDay}
     * @memberof HolidayPayPolicyFederalHolidaysInner
     */
    'memorial_day'?: HolidayPayPolicyFederalHolidaysInnerNewYearsDay;
    /**
     * 
     * @type {HolidayPayPolicyFederalHolidaysInnerNewYearsDay}
     * @memberof HolidayPayPolicyFederalHolidaysInner
     */
    'juneteenth'?: HolidayPayPolicyFederalHolidaysInnerNewYearsDay;
    /**
     * 
     * @type {HolidayPayPolicyFederalHolidaysInnerNewYearsDay}
     * @memberof HolidayPayPolicyFederalHolidaysInner
     */
    'independence_day'?: HolidayPayPolicyFederalHolidaysInnerNewYearsDay;
    /**
     * 
     * @type {HolidayPayPolicyFederalHolidaysInnerNewYearsDay}
     * @memberof HolidayPayPolicyFederalHolidaysInner
     */
    'labor_day'?: HolidayPayPolicyFederalHolidaysInnerNewYearsDay;
    /**
     * 
     * @type {HolidayPayPolicyFederalHolidaysInnerNewYearsDay}
     * @memberof HolidayPayPolicyFederalHolidaysInner
     */
    'columbus_day'?: HolidayPayPolicyFederalHolidaysInnerNewYearsDay;
    /**
     * 
     * @type {HolidayPayPolicyFederalHolidaysInnerNewYearsDay}
     * @memberof HolidayPayPolicyFederalHolidaysInner
     */
    'veterans_day'?: HolidayPayPolicyFederalHolidaysInnerNewYearsDay;
    /**
     * 
     * @type {HolidayPayPolicyFederalHolidaysInnerNewYearsDay}
     * @memberof HolidayPayPolicyFederalHolidaysInner
     */
    'thanksgiving'?: HolidayPayPolicyFederalHolidaysInnerNewYearsDay;
}

