/*
Gusto API

Welcome to Gusto's Embedded Payroll API documentation!

The version of the OpenAPI document: 2024-03-01
Contact: developer@gusto.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The minimum wage record you want to apply to the compensation
 * @export
 * @interface JobsAndCompensationsCreateCompensationRequestMinimumWagesInner
 */
export interface JobsAndCompensationsCreateCompensationRequestMinimumWagesInner {
    /**
     * The UUID of the minimum wage record. Required if adjust_for_minimum_wage set to true
     * @type {string}
     * @memberof JobsAndCompensationsCreateCompensationRequestMinimumWagesInner
     */
    'uuid'?: string;
}

