/*
Gusto API

Welcome to Gusto's Embedded Payroll API documentation!

The version of the OpenAPI document: 2024-03-01
Contact: developer@gusto.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The representation of an address in Gusto.
 * @export
 * @interface Location
 */
export interface Location {
    /**
     * The current version of the object. See the [versioning guide](https://docs.gusto.com/embedded-payroll/docs/idempotency) for information on how to use this field.
     * @type {string}
     * @memberof Location
     */
    'version'?: string;
    /**
     * The UUID of the location object.
     * @type {string}
     * @memberof Location
     */
    'uuid'?: string;
    /**
     * The UUID for the company to which the location belongs. Only included if the location belongs to a company.
     * @type {string}
     * @memberof Location
     */
    'company_uuid'?: string;
    /**
     * The phone number for the location. Required for company locations. Optional for employee locations.
     * @type {string}
     * @memberof Location
     */
    'phone_number'?: string;
    /**
     * 
     * @type {string}
     * @memberof Location
     */
    'street_1'?: string;
    /**
     * 
     * @type {string}
     * @memberof Location
     */
    'street_2'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Location
     */
    'city'?: string;
    /**
     * 
     * @type {string}
     * @memberof Location
     */
    'state'?: string;
    /**
     * 
     * @type {string}
     * @memberof Location
     */
    'zip'?: string;
    /**
     * 
     * @type {string}
     * @memberof Location
     */
    'country'?: string;
    /**
     * The status of the location. Inactive locations have been deleted, but may still have historical data associated with them.
     * @type {boolean}
     * @memberof Location
     */
    'active'?: boolean;
    /**
     * Specifies if the location is the company\'s mailing address. Only included if the location belongs to a company.
     * @type {boolean}
     * @memberof Location
     */
    'mailing_address'?: boolean | null;
    /**
     * Specifies if the location is the company\'s filing address. Only included if the location belongs to a company.
     * @type {boolean}
     * @memberof Location
     */
    'filing_address'?: boolean | null;
    /**
     * Datetime for when location is created
     * @type {string}
     * @memberof Location
     */
    'created_at'?: string;
    /**
     * Datetime for when location is updated
     * @type {string}
     * @memberof Location
     */
    'updated_at'?: string;
}

