/*
Gusto API

Welcome to Gusto's Embedded Payroll API documentation!

The version of the OpenAPI document: 2024-03-01
Contact: developer@gusto.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface LocationsCreateCompanyLocationRequest1
 */
export interface LocationsCreateCompanyLocationRequest1 {
    /**
     * 
     * @type {string}
     * @memberof LocationsCreateCompanyLocationRequest1
     */
    'phone_number': string;
    /**
     * 
     * @type {string}
     * @memberof LocationsCreateCompanyLocationRequest1
     */
    'street_1': string;
    /**
     * 
     * @type {string}
     * @memberof LocationsCreateCompanyLocationRequest1
     */
    'street_2': string | null;
    /**
     * 
     * @type {string}
     * @memberof LocationsCreateCompanyLocationRequest1
     */
    'city': string;
    /**
     * 
     * @type {string}
     * @memberof LocationsCreateCompanyLocationRequest1
     */
    'state': string;
    /**
     * 
     * @type {string}
     * @memberof LocationsCreateCompanyLocationRequest1
     */
    'zip': string;
    /**
     * 
     * @type {string}
     * @memberof LocationsCreateCompanyLocationRequest1
     */
    'country': string;
}

