/*
Gusto API

Welcome to Gusto's Embedded Payroll API documentation!

The version of the OpenAPI document: 2024-03-01
Contact: developer@gusto.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface LocationsCreateCompanyLocationRequest
 */
export interface LocationsCreateCompanyLocationRequest {
    /**
     * 
     * @type {string}
     * @memberof LocationsCreateCompanyLocationRequest
     */
    'phone_number': string;
    /**
     * 
     * @type {string}
     * @memberof LocationsCreateCompanyLocationRequest
     */
    'street_1': string;
    /**
     * 
     * @type {string}
     * @memberof LocationsCreateCompanyLocationRequest
     */
    'street_2'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LocationsCreateCompanyLocationRequest
     */
    'city': string;
    /**
     * 
     * @type {string}
     * @memberof LocationsCreateCompanyLocationRequest
     */
    'state': string;
    /**
     * 
     * @type {string}
     * @memberof LocationsCreateCompanyLocationRequest
     */
    'zip': string;
    /**
     * 
     * @type {string}
     * @memberof LocationsCreateCompanyLocationRequest
     */
    'country'?: string;
    /**
     * Specify if this location is the company\'s mailing address.
     * @type {boolean}
     * @memberof LocationsCreateCompanyLocationRequest
     */
    'mailing_address'?: boolean;
    /**
     * Specify if this location is the company\'s filing address.
     * @type {boolean}
     * @memberof LocationsCreateCompanyLocationRequest
     */
    'filing_address'?: boolean;
}

