/*
Gusto API

Welcome to Gusto's Embedded Payroll API documentation!

The version of the OpenAPI document: 2024-03-01
Contact: developer@gusto.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface OnboardingStep
 */
export interface OnboardingStep {
    /**
     * User-friendly description of the onboarding step.
     * @type {string}
     * @memberof OnboardingStep
     */
    'title'?: string;
    /**
     * String identifier for the onboarding step.
     * @type {string}
     * @memberof OnboardingStep
     */
    'id'?: string;
    /**
     * When true, this step has been completed.
     * @type {boolean}
     * @memberof OnboardingStep
     */
    'required'?: boolean;
    /**
     * When true, this step has been completed.
     * @type {boolean}
     * @memberof OnboardingStep
     */
    'completed'?: boolean;
    /**
     * A list of onboarding steps required to begin this step.
     * @type {Array<string>}
     * @memberof OnboardingStep
     */
    'requirements'?: Array<string>;
}

