/*
Gusto API

Welcome to Gusto's Embedded Payroll API documentation!

The version of the OpenAPI document: 2024-03-01
Contact: developer@gusto.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PaidHolidaysSchema
 */
export interface PaidHolidaysSchema {
    /**
     * the holiday\'s identifier
     * @type {string}
     * @memberof PaidHolidaysSchema
     */
    'holiday_key'?: string;
    /**
     * the holiday\'s official name
     * @type {string}
     * @memberof PaidHolidaysSchema
     */
    'holiday_name'?: string;
    /**
     * the holiday\'s start date (YYYY-MM-DD)
     * @type {string}
     * @memberof PaidHolidaysSchema
     */
    'start_date'?: string;
    /**
     * the holiday\'s end date (YYYY-MM-DD)
     * @type {string}
     * @memberof PaidHolidaysSchema
     */
    'end_date'?: string;
}

