/*
Gusto API

Welcome to Gusto's Embedded Payroll API documentation!

The version of the OpenAPI document: 2024-03-01
Contact: developer@gusto.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PayScheduleAssignmentBodyDepartmentsInner } from './pay-schedule-assignment-body-departments-inner';
import { PayScheduleAssignmentBodyEmployeesInner } from './pay-schedule-assignment-body-employees-inner';

/**
 * 
 * @export
 * @interface PayScheduleAssignmentBody
 */
export interface PayScheduleAssignmentBody {
    /**
     * The pay schedule assignment type.
     * @type {string}
     * @memberof PayScheduleAssignmentBody
     */
    'type': PayScheduleAssignmentBodyTypeEnum;
    /**
     * Pay schedule for hourly employees.
     * @type {string}
     * @memberof PayScheduleAssignmentBody
     */
    'hourly_pay_schedule_uuid'?: string;
    /**
     * Pay schedule for salaried employees.
     * @type {string}
     * @memberof PayScheduleAssignmentBody
     */
    'salaried_pay_schedule_uuid'?: string;
    /**
     * Default pay schedule for employees.
     * @type {string}
     * @memberof PayScheduleAssignmentBody
     */
    'default_pay_schedule_uuid'?: string;
    /**
     * List of employees and their pay schedules.
     * @type {Array<PayScheduleAssignmentBodyEmployeesInner>}
     * @memberof PayScheduleAssignmentBody
     */
    'employees'?: Array<PayScheduleAssignmentBodyEmployeesInner>;
    /**
     * List of departments and their pay schedules.
     * @type {Array<PayScheduleAssignmentBodyDepartmentsInner>}
     * @memberof PayScheduleAssignmentBody
     */
    'departments'?: Array<PayScheduleAssignmentBodyDepartmentsInner>;
}

type PayScheduleAssignmentBodyTypeEnum = 'single' | 'hourly_salaried' | 'by_employee' | 'by_department'


