/*
Gusto API

Welcome to Gusto's Embedded Payroll API documentation!

The version of the OpenAPI document: 2024-03-01
Contact: developer@gusto.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PayScheduleAssignmentBodyDepartmentsInner
 */
export interface PayScheduleAssignmentBodyDepartmentsInner {
    /**
     * Department UUID
     * @type {string}
     * @memberof PayScheduleAssignmentBodyDepartmentsInner
     */
    'department_uuid'?: string;
    /**
     * Pay schedule UUID
     * @type {string}
     * @memberof PayScheduleAssignmentBodyDepartmentsInner
     */
    'pay_schedule_uuid'?: string;
}

