/*
Gusto API

Welcome to Gusto's Embedded Payroll API documentation!

The version of the OpenAPI document: 2024-03-01
Contact: developer@gusto.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Pay schedule assignment transition pay period information.
 * @export
 * @interface PayScheduleAssignmentTransitionPayPeriod
 */
export interface PayScheduleAssignmentTransitionPayPeriod {
    /**
     * Pay period start date.
     * @type {string}
     * @memberof PayScheduleAssignmentTransitionPayPeriod
     */
    'start_date'?: string;
    /**
     * Pay period end date.
     * @type {string}
     * @memberof PayScheduleAssignmentTransitionPayPeriod
     */
    'end_date'?: string;
}

