/*
Gusto API

Welcome to Gusto's Embedded Payroll API documentation!

The version of the OpenAPI document: 2024-03-01
Contact: developer@gusto.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PayPeriodPayroll } from './pay-period-payroll';

/**
 * The representation of a pay period.
 * @export
 * @interface PayPeriod
 */
export interface PayPeriod {
    /**
     * The start date, inclusive, of the pay period.
     * @type {string}
     * @memberof PayPeriod
     */
    'start_date'?: string;
    /**
     * The end date, inclusive, of the pay period.
     * @type {string}
     * @memberof PayPeriod
     */
    'end_date'?: string;
    /**
     * A unique identifier of the pay schedule to which the pay period belongs.
     * @type {string}
     * @memberof PayPeriod
     */
    'pay_schedule_uuid'?: string;
    /**
     * 
     * @type {PayPeriodPayroll}
     * @memberof PayPeriod
     */
    'payroll'?: PayPeriodPayroll;
}

