/*
Gusto API

Welcome to Gusto's Embedded Payroll API documentation!

The version of the OpenAPI document: 2024-03-01
Contact: developer@gusto.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PayrollsCalculateGrossUpRequest
 */
export interface PayrollsCalculateGrossUpRequest {
    /**
     * Employee UUID
     * @type {string}
     * @memberof PayrollsCalculateGrossUpRequest
     */
    'employee_uuid': string;
    /**
     * Employee net earnings
     * @type {string}
     * @memberof PayrollsCalculateGrossUpRequest
     */
    'net_pay': string;
}

