/*
Gusto API

Welcome to Gusto's Embedded Payroll API documentation!

The version of the OpenAPI document: 2024-03-01
Contact: developer@gusto.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The subtotals for the payroll.
 * @export
 * @interface PayrollReceiptTotals
 */
export interface PayrollReceiptTotals {
    /**
     * The total company debit for the payroll.
     * @type {string}
     * @memberof PayrollReceiptTotals
     */
    'company_debit'?: string;
    /**
     * The total company net pay for the payroll.
     * @type {string}
     * @memberof PayrollReceiptTotals
     */
    'net_pay_debit'?: string;
    /**
     * The total child support debit for the payroll.
     * @type {string}
     * @memberof PayrollReceiptTotals
     */
    'child_support_debit'?: string;
    /**
     * The total reimbursements for the payroll.
     * @type {string}
     * @memberof PayrollReceiptTotals
     */
    'reimbursement_debit'?: string;
    /**
     * The total tax debit for the payroll.
     * @type {string}
     * @memberof PayrollReceiptTotals
     */
    'tax_debit'?: string;
}

