/*
Gusto API

Welcome to Gusto's Embedded Payroll API documentation!

The version of the OpenAPI document: 2024-03-01
Contact: developer@gusto.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The payment schedule tax rate the payroll is based on. Only included for off-cycle payrolls.
 * @export
 * @enum {string}
 */
export type PayrollWithholdingPayPeriodType = 'Every week' | 'Every other week' | 'Twice per month' | 'Monthly' | 'Quarterly' | 'Semiannually' | 'Annually'

