/*
Gusto API

Welcome to Gusto's Embedded Payroll API documentation!

The version of the OpenAPI document: 2024-03-01
Contact: developer@gusto.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The subtotals for the payroll.
 * @export
 * @interface PayrollTotalsType
 */
export interface PayrollTotalsType {
    /**
     * The total company debit for the payroll.
     * @type {string}
     * @memberof PayrollTotalsType
     */
    'company_debit'?: string;
    /**
     * The total company net pay for the payroll.
     * @type {string}
     * @memberof PayrollTotalsType
     */
    'net_pay_debit'?: string;
    /**
     * The total tax debit for the payroll.
     * @type {string}
     * @memberof PayrollTotalsType
     */
    'tax_debit'?: string;
    /**
     * The total reimbursement debit for the payroll.
     * @type {string}
     * @memberof PayrollTotalsType
     */
    'reimbursement_debit'?: string;
    /**
     * The total child support debit for the payroll.
     * @type {string}
     * @memberof PayrollTotalsType
     */
    'child_support_debit'?: string;
    /**
     * The total reimbursements for the payroll.
     * @type {string}
     * @memberof PayrollTotalsType
     */
    'reimbursements'?: string;
    /**
     * The net pay amount for the payroll.
     * @type {string}
     * @memberof PayrollTotalsType
     */
    'net_pay'?: string;
    /**
     * The gross pay amount for the payroll.
     * @type {string}
     * @memberof PayrollTotalsType
     */
    'gross_pay'?: string;
    /**
     * The total employee bonuses amount for the payroll.
     * @type {string}
     * @memberof PayrollTotalsType
     */
    'employee_bonuses'?: string;
    /**
     * The total employee commissions amount for the payroll.
     * @type {string}
     * @memberof PayrollTotalsType
     */
    'employee_commissions'?: string;
    /**
     * The total employee cash tips amount for the payroll.
     * @type {string}
     * @memberof PayrollTotalsType
     */
    'employee_cash_tips'?: string;
    /**
     * The total employee paycheck tips amount for the payroll.
     * @type {string}
     * @memberof PayrollTotalsType
     */
    'employee_paycheck_tips'?: string;
    /**
     * The total additional earnings amount for the payroll.
     * @type {string}
     * @memberof PayrollTotalsType
     */
    'additional_earnings'?: string;
    /**
     * The total owner\'s draw for the payroll.
     * @type {string}
     * @memberof PayrollTotalsType
     */
    'owners_draw'?: string;
    /**
     * The total check amount for the payroll.
     * @type {string}
     * @memberof PayrollTotalsType
     */
    'check_amount'?: string;
    /**
     * The total amount of employer paid taxes for the payroll.
     * @type {string}
     * @memberof PayrollTotalsType
     */
    'employer_taxes'?: string;
    /**
     * The total amount of employee paid taxes for the payroll.
     * @type {string}
     * @memberof PayrollTotalsType
     */
    'employee_taxes'?: string;
    /**
     * The total amount of company contributed benefits for the payroll.
     * @type {string}
     * @memberof PayrollTotalsType
     */
    'benefits'?: string;
    /**
     * The total amount of employee deducted benefits for the payroll.
     * @type {string}
     * @memberof PayrollTotalsType
     */
    'employee_benefits_deductions'?: string;
    /**
     * The total amount of payroll taxes deferred for the payroll, such as allowed by the CARES act.
     * @type {string}
     * @memberof PayrollTotalsType
     */
    'deferred_payroll_taxes'?: string;
}

