/*
Gusto API

Welcome to Gusto's Embedded Payroll API documentation!

The version of the OpenAPI document: 2024-03-01
Contact: developer@gusto.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Only applicable when a payroll is moved to four day processing instead of fast ach.
 * @export
 * @interface PayrollPaymentSpeedChangedType
 */
export interface PayrollPaymentSpeedChangedType {
    /**
     * Original check date when fast ach applies.
     * @type {string}
     * @memberof PayrollPaymentSpeedChangedType
     */
    'original_check_date'?: string;
    /**
     * Current check date.
     * @type {string}
     * @memberof PayrollPaymentSpeedChangedType
     */
    'current_check_date'?: string;
    /**
     * Original debit date when fast ach applies.
     * @type {number}
     * @memberof PayrollPaymentSpeedChangedType
     */
    'original_debit_date'?: number;
    /**
     * Current debit date.
     * @type {string}
     * @memberof PayrollPaymentSpeedChangedType
     */
    'current_debit_date'?: string;
    /**
     * The reason why the payroll is moved to four day.
     * @type {string}
     * @memberof PayrollPaymentSpeedChangedType
     */
    'reason'?: string;
}

