/*
Gusto API

Welcome to Gusto's Embedded Payroll API documentation!

The version of the OpenAPI document: 2024-03-01
Contact: developer@gusto.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PayrollBlockersError } from './payroll-blockers-error';
import { PayrollBlockersErrorErrorsInner } from './payroll-blockers-error-errors-inner';
import { UnprocessableEntityErrorObject } from './unprocessable-entity-error-object';

/**
 * @type PayrollsSkipPayrollResponse
 * @export
 */
export type PayrollsSkipPayrollResponse = PayrollBlockersError | UnprocessableEntityErrorObject;


