/*
Gusto API

Welcome to Gusto's Embedded Payroll API documentation!

The version of the OpenAPI document: 2024-03-01
Contact: developer@gusto.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { SignatoryHomeAddress } from './signatory-home-address';

/**
 * The representation of a company\'s signatory
 * @export
 * @interface Signatory
 */
export interface Signatory {
    /**
     * 
     * @type {string}
     * @memberof Signatory
     */
    'title'?: string | null;
    /**
     * The current version of the signatory. See the [versioning guide](https://docs.gusto.com/embedded-payroll/docs/idempotency) for information on how to use this field.
     * @type {string}
     * @memberof Signatory
     */
    'version'?: string;
    /**
     * 
     * @type {string}
     * @memberof Signatory
     */
    'uuid'?: string;
    /**
     * 
     * @type {string}
     * @memberof Signatory
     */
    'first_name'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Signatory
     */
    'last_name'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Signatory
     */
    'phone'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Signatory
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof Signatory
     */
    'birthday'?: string | null;
    /**
     * Whether or not the signatory is also the payroll admin of the company.
     * @type {boolean}
     * @memberof Signatory
     */
    'is_admin'?: boolean;
    /**
     * Indicates whether the signatory has an SSN in Gusto.
     * @type {boolean}
     * @memberof Signatory
     */
    'has_ssn'?: boolean;
    /**
     * |   |   | |---|---| |__Status__| __Description__ | | Pass | Signatory can sign all forms | | Fail | Signatory cannot sign forms | | Skipped | Signatory cannot sign Form 8655 until the form is manually uploaded as wet-signed | | null | Identity verification process has not been completed |
     * @type {string}
     * @memberof Signatory
     */
    'identity_verification_status'?: SignatoryIdentityVerificationStatusEnum;
    /**
     * 
     * @type {SignatoryHomeAddress}
     * @memberof Signatory
     */
    'home_address'?: SignatoryHomeAddress | null;
}

type SignatoryIdentityVerificationStatusEnum = 'Pass' | 'Fail' | 'Skipped'


