/*
Gusto API

Welcome to Gusto's Embedded Payroll API documentation!

The version of the OpenAPI document: 2024-03-01
Contact: developer@gusto.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { SignatoriesUpdateRequestHomeAddress } from './signatories-update-request-home-address';

/**
 * 
 * @export
 * @interface SignatoriesUpdateRequest
 */
export interface SignatoriesUpdateRequest {
    /**
     * 
     * @type {string}
     * @memberof SignatoriesUpdateRequest
     */
    'title'?: string;
    /**
     * The current version of the object. See the versioning guide for information on how to use this field.
     * @type {string}
     * @memberof SignatoriesUpdateRequest
     */
    'version'?: string;
    /**
     * 
     * @type {string}
     * @memberof SignatoriesUpdateRequest
     */
    'first_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof SignatoriesUpdateRequest
     */
    'middle_initial'?: string;
    /**
     * 
     * @type {string}
     * @memberof SignatoriesUpdateRequest
     */
    'last_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof SignatoriesUpdateRequest
     */
    'phone'?: string;
    /**
     * 
     * @type {string}
     * @memberof SignatoriesUpdateRequest
     */
    'birthday'?: string;
    /**
     * 
     * @type {string}
     * @memberof SignatoriesUpdateRequest
     */
    'ssn'?: string;
    /**
     * 
     * @type {SignatoriesUpdateRequestHomeAddress}
     * @memberof SignatoriesUpdateRequest
     */
    'home_address'?: SignatoriesUpdateRequestHomeAddress;
}

