/*
Gusto API

Welcome to Gusto's Embedded Payroll API documentation!

The version of the OpenAPI document: 2024-03-01
Contact: developer@gusto.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface SignatoriesUpdateRequestHomeAddress
 */
export interface SignatoriesUpdateRequestHomeAddress {
    /**
     * 
     * @type {string}
     * @memberof SignatoriesUpdateRequestHomeAddress
     */
    'street_1'?: string;
    /**
     * 
     * @type {string}
     * @memberof SignatoriesUpdateRequestHomeAddress
     */
    'street_2'?: string;
    /**
     * 
     * @type {string}
     * @memberof SignatoriesUpdateRequestHomeAddress
     */
    'city'?: string;
    /**
     * 
     * @type {string}
     * @memberof SignatoriesUpdateRequestHomeAddress
     */
    'state'?: string;
    /**
     * 
     * @type {string}
     * @memberof SignatoriesUpdateRequestHomeAddress
     */
    'zip'?: string;
}

