/*
Gusto API

Welcome to Gusto's Embedded Payroll API documentation!

The version of the OpenAPI document: 2024-03-01
Contact: developer@gusto.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { SignatoriesCreateSignatoryWithCompleteInformationRequestHomeAddress } from './signatories-create-signatory-with-complete-information-request-home-address';

/**
 * 
 * @export
 * @interface SignatoriesCreateSignatoryWithCompleteInformationRequest
 */
export interface SignatoriesCreateSignatoryWithCompleteInformationRequest {
    /**
     * 
     * @type {string}
     * @memberof SignatoriesCreateSignatoryWithCompleteInformationRequest
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof SignatoriesCreateSignatoryWithCompleteInformationRequest
     */
    'ssn': string;
    /**
     * 
     * @type {string}
     * @memberof SignatoriesCreateSignatoryWithCompleteInformationRequest
     */
    'first_name': string;
    /**
     * 
     * @type {string}
     * @memberof SignatoriesCreateSignatoryWithCompleteInformationRequest
     */
    'middle_initial'?: string;
    /**
     * 
     * @type {string}
     * @memberof SignatoriesCreateSignatoryWithCompleteInformationRequest
     */
    'last_name': string;
    /**
     * 
     * @type {string}
     * @memberof SignatoriesCreateSignatoryWithCompleteInformationRequest
     */
    'email': string;
    /**
     * 
     * @type {string}
     * @memberof SignatoriesCreateSignatoryWithCompleteInformationRequest
     */
    'phone': string;
    /**
     * 
     * @type {string}
     * @memberof SignatoriesCreateSignatoryWithCompleteInformationRequest
     */
    'birthday': string;
    /**
     * 
     * @type {SignatoriesCreateSignatoryWithCompleteInformationRequestHomeAddress}
     * @memberof SignatoriesCreateSignatoryWithCompleteInformationRequest
     */
    'home_address': SignatoriesCreateSignatoryWithCompleteInformationRequestHomeAddress;
}

