/*
Gusto API

Welcome to Gusto's Embedded Payroll API documentation!

The version of the OpenAPI document: 2024-03-01
Contact: developer@gusto.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Possible tax liabilities selections.
 * @export
 * @interface TaxLiabilitiesSelectionsPossibleLiabilities
 */
export interface TaxLiabilitiesSelectionsPossibleLiabilities {
    /**
     * Liability amount.
     * @type {string}
     * @memberof TaxLiabilitiesSelectionsPossibleLiabilities
     */
    'liability_amount'?: string;
    /**
     * The external payroll check date.
     * @type {string}
     * @memberof TaxLiabilitiesSelectionsPossibleLiabilities
     */
    'payroll_check_date'?: string;
    /**
     * The UUID of the external payroll.
     * @type {string}
     * @memberof TaxLiabilitiesSelectionsPossibleLiabilities
     */
    'external_payroll_uuid'?: string;
}

