/*
Gusto API

Welcome to Gusto's Embedded Payroll API documentation!

The version of the OpenAPI document: 2024-03-01
Contact: developer@gusto.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { TaxRequirement } from './tax-requirement';

/**
 * 
 * @export
 * @interface TaxRequirementSet
 */
export interface TaxRequirementSet {
    /**
     * One of the two-letter state abbreviations for the fifty United States and the District of Columbia (DC)
     * @type {string}
     * @memberof TaxRequirementSet
     */
    'state'?: string;
    /**
     * An identifier for a set of requirements. A list of requirement sets can contain multiple sets with the same `key` and different `effective_from` values.
     * @type {string}
     * @memberof TaxRequirementSet
     */
    'key'?: string;
    /**
     * Customer facing label for the requirement set, e.g. \"Registrations\"
     * @type {string}
     * @memberof TaxRequirementSet
     */
    'label'?: string;
    /**
     * An ISO 8601 formatted date representing the date values became effective. Some requirement sets are effective dated, while others are not. Multiple requirement sets for the same state/key can/will exist with unique effective dates. If a requirement set is has an `effective_from` value, all requirement sets with the same key will also have an `effective_from` value.
     * @type {string}
     * @memberof TaxRequirementSet
     */
    'effective_from'?: string | null;
    /**
     * 
     * @type {Array<TaxRequirement>}
     * @memberof TaxRequirementSet
     */
    'requirements'?: Array<TaxRequirement>;
}

